### ISSUE TITLE
Docker compose - setup Wordpress in 2 container

### ISSUE THREAD

**Issue by jyothymolvt** [jyothymolvt/-Docker#2]
**This compose.yaml file sets up a WordPress site with a MySQL database using Docker Compose.**

🔧 Services

WordPress (wpserver):
    Uses the latest wordpress image.
    Connects to the MySQL container using a private IP.
    Stores site data in a named volume wordpress_data.

MySQL (dbserver):
    Uses the latest mysql image.
    Initializes with a database wpdb, user wpuser, and password.
    Stores database data in a named volume db_data.

🌐 Network
Both services share a custom Docker network wordpress_network.

💾 Volumes
wordpress_data — persists WordPress content.
db_data — persists MySQL data.

#**cat compose.yaml** 

```
services:
    wordpress:
        image: wordpress:latest
        container_name: wpserver
        restart: always
        networks:
            - wordpress_network
        depends_on:
            - db
        volumes:
            - wordpress_data:/var/www/html
        environment:
            WORDPRESS_DB_HOST: 172.21.0.2
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: Tqwe123!@#
            WORDPRESS_DB_NAME: wpdb
    db:
        image: mysql:latest
        container_name: dbserver
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Qasd123!@#
            MYSQL_DATABASE: wpdb
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: Tqwe123!@#
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:
```

Commands

```
#sudo docker compose up -d
# sudo docker compose down -v

```
